apiVersion: 1

#  Points de contact (où envoyer les alertes) 
contactPoints:
  - orgId: 1
    name: DevOps Team
    receivers:
      # Alerte visible dans Grafana UI (toujours active)
      - uid: grafana-default-email
        type: email
        settings:
          addresses: "ton.email@exemple.com"   # ← change ici
          singleEmail: false
        disableResolveMessage: false

#  Politique de routage des alertes 
policies:
  - orgId: 1
    receiver: DevOps Team
    group_by: ['alertname', 'job']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    routes:
      # Alertes critiques -> notif immédiate
      - receiver: DevOps Team
        matchers:
          - severity = critical
        group_wait: 10s
        repeat_interval: 15m
      # Alertes warning -> notif groupée
      - receiver: DevOps Team
        matchers:
          - severity = warning
        group_wait: 1m
        repeat_interval: 1h
